import { StyleSheet, Dimensions } from 'react-native';

const { width: screenWidth, height: screenHeight } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    padding: 10,
    backgroundColor: '#fff',
    marginBottom: 5,
  },
  ownMessageContainer: {
    backgroundColor: '#e3f2fd',
    alignSelf: 'flex-end',
    marginLeft: 50,
    marginRight: 10,
    borderRadius: 15,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
  },
  ownMessageHeader: {
    justifyContent: 'flex-end',
  },
  avatar: {
    width: 30,
    height: 30,
    borderRadius: 15,
    marginRight: 8,
  },
  name: {
    fontWeight: '600',
    fontSize: 14,
    flex: 1,
    color: '#007AFF',
  },
  ownMessageName: {
    color: '#1976d2',
    textAlign: 'right',
  },
  time: {
    fontSize: 12,
    color: '#666',
    marginLeft: 8,
  },
  replyContainer: {
    backgroundColor: '#f0f0f0',
    padding: 8,
    marginBottom: 5,
    borderRadius: 5,
  },
  replyText: {
    fontSize: 12,
    color: '#666',
    fontStyle: 'italic',
  },
  content: {
    marginBottom: 5,
  },
  ownMessageContent: {
    alignItems: 'flex-end',
  },
  text: {
    fontSize: 16,
    lineHeight: 20,
  },
  ownMessageText: {
    color: '#1565c0',
  },
  image: {
    width: 200,
    height: 150,
    borderRadius: 8,
  },
  edited: {
    fontSize: 12,
    color: '#999',
    fontStyle: 'italic',
  },
  reactionsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 5,
  },
  reaction: {
    backgroundColor: '#f0f0f0',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginRight: 5,
    marginBottom: 2,
  },
  reactionText: {
    fontSize: 12,
  },
  reactionCount: {
    fontSize: 10,
    color: '#666',
    marginLeft: 2,
    fontWeight: 'bold',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  reactionModal: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 20,
    minWidth: 250,
  },
  reactionModalTitle: {
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 15,
  },
  reactionGrid: {
    maxHeight: 200,
  },
  reactionOption: {
    width: 50,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    margin: 5,
    backgroundColor: '#f8f8f8',
    borderRadius: 25,
  },
  reactionEmoji: {
    fontSize: 24,
  },
  imageModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeButton: {
    position: 'absolute',
    top: 50,
    right: 20,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  closeButtonText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
  },
  imageModalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  fullScreenImage: {
    width: screenWidth,
    height: screenHeight * 0.8,
  },
  participantModal: {
    backgroundColor: '#fff',
    borderRadius: 12,
    margin: 20,
    maxHeight: screenHeight * 0.8,
  },
  participantContent: {
    padding: 20,
  },
  participantHeader: {
    alignItems: 'center',
    marginBottom: 20,
  },
  participantAvatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    marginBottom: 10,
  },
  participantName: {
    fontSize: 20,
    fontWeight: '600',
  },
  currentUserIndicator: {
    fontSize: 12,
    color: '#007AFF',
    backgroundColor: '#e3f2fd',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
    marginTop: 5,
  },
  participantSection: {
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#666',
    marginBottom: 5,
  },
  sectionText: {
    fontSize: 16,
    lineHeight: 22,
  },
  reactionDetailsModal: {
    backgroundColor: '#fff',
    borderRadius: 12,
    margin: 20,
    maxHeight: screenHeight * 0.8,
    minHeight: 300,
    width: screenWidth - 40,
  },
  reactionDetailsTitle: {
    fontSize: 18,
    fontWeight: '600',
    textAlign: 'center',
    flex: 1,
  },
  reactionDetailsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  reactionDetailsCloseButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#f0f0f0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  reactionDetailsCloseText: {
    fontSize: 16,
    color: '#666',
    fontWeight: 'bold',
  },
  bottomSheetOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
    position: 'relative',
  },
  bottomSheetOutsideOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'transparent',
  },
  bottomSheetContainer: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: screenHeight * 0.9,
    minHeight: 300,
    width: screenWidth,
  },
  bottomSheetHandle: {
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  bottomSheetHandleBar: {
    width: 40,
    height: 4,
    backgroundColor: '#ddd',
    borderRadius: 2,
  },
  bottomSheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  bottomSheetTitle: {
    fontSize: 18,
    fontWeight: '600',
    flex: 1,
  },
  bottomSheetCloseButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#f0f0f0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bottomSheetCloseText: {
    fontSize: 16,
    color: '#666',
    fontWeight: 'bold',
  },
  bottomSheetContent: {
    flex: 1,
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  bottomSheetScrollView: {
    flex: 1,
  },
  bottomSheetScrollContent: {
    paddingVertical: 15,
    flexGrow: 1,
  },
  bottomSheetItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 15,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  bottomSheetEmoji: {
    fontSize: 24,
    marginRight: 15,
  },
  bottomSheetName: {
    fontSize: 18,
    color: '#333',
    flex: 1,
    fontWeight: '500',
  },
  reactionDetailsList: {
    flex: 1,
  },
  reactionDetailsContent: {
    paddingVertical: 10,
    flexGrow: 1,
  },
  reactionDetailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 5,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  reactionDetailEmoji: {
    fontSize: 20,
    marginRight: 10,
  },
  reactionDetailName: {
    fontSize: 16,
    fontWeight: '500',
  },

  editButton: {
    alignSelf: 'flex-start',
    marginTop: 5,
    marginLeft: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#f0f0f0',
    borderRadius: 15,
  },
  editButtonText: {
    fontSize: 12,
    color: '#FF9500',
    fontWeight: '500',
  },
  editModal: {
    backgroundColor: '#fff',
    borderRadius: 12,
    margin: 20,
    padding: 20,
    maxHeight: '80%',
  },
  editModalTitle: {
    fontSize: 18,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 15,
  },
  editInput: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    minHeight: 100,
    textAlignVertical: 'top',
    marginBottom: 15,
  },
  editButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  editCancelButton: {
    flex: 1,
    backgroundColor: '#f0f0f0',
    paddingVertical: 12,
    borderRadius: 8,
    marginRight: 8,
    alignItems: 'center',
  },
  editCancelText: {
    fontSize: 16,
    color: '#666',
    fontWeight: '500',
  },
  editSaveButton: {
    flex: 1,
    backgroundColor: '#007AFF',
    paddingVertical: 12,
    borderRadius: 8,
    marginLeft: 8,
    alignItems: 'center',
  },
  editSaveText: {
    fontSize: 16,
    color: '#fff',
    fontWeight: '500',
  },
  editExpired: {
    fontSize: 10,
    color: '#999',
    fontStyle: 'italic',
    marginTop: 2,
  },
  contextMenu: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 8,
    margin: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  contextMenuItem: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
  },
  contextMenuText: {
    fontSize: 16,
    color: '#333',
    fontWeight: '500',
  },
}); 